services:
  - type: web
    name: lapcompare-control-plane
    env: python
    rootDir: control-plane
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    plan: free
    envVars:
      - key: B2_S3_ENDPOINT
        sync: false
      - key: B2_REGION
        sync: false
      - key: B2_BUCKET
        sync: false
      - key: B2_KEY_ID
        sync: false
      - key: B2_APP_KEY
        sync: false
      - key: B2_PREFIX
        sync: false
